In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import nltk
import re
from os import replace
import sklearn
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from xgboost import XGBRegressor
from sklearn import metrics

In [ ]:
cal=pd.read_csv('/content/calories - calories (1).csv')

In [ ]:
cal.head()

    User_ID  Calories
0  14733363       231
1  14861698        66
2  11179863        26
3  16180408        71
4  17771927        35

In [ ]:
cal.isnull().sum()

User_ID     0
Calories    0
dtype: int64

In [ ]:
exersice=pd.read_csv('/content/exercise - exercise (1).csv')

In [ ]:
exersice.head()

    User_ID  Gender  Age  Height  Weight  Duration  Heart_Rate  Body_Temp
0  14733363    male   68     190      94        29         105       40.8
1  14861698  female   20     166      60        14          94       40.3
2  11179863    male   69     179      79         5          88       38.7
3  16180408  female   34     179      71        13         100       40.5
4  17771927  female   27     154      58        10          81       39.8

In [ ]:
exersice.isnull().sum()

User_ID       0
Gender        0
Age           0
Height        0
Weight        0
Duration      0
Heart_Rate    0
Body_Temp     0
dtype: int64

In [ ]:
cal_data=pd.concat([exersice,cal['Calories']],axis=1)

In [ ]:
cal_data.head()

,User_ID,Gender,Age,Height,Weight,Duration,Heart_Rate,Body_Temp,Calories
0,14733363,male,68,190,94,29,105,40.8,231
1,14861698,female,20,166,60,14,94,40.3,66
2,11179863,male,69,179,79,5,88,38.7,26
3,16180408,female,34,179,71,13,100,40.5,71
4,17771927,female,27,154,58,10,81,39.8,35

In [ ]:
cal_data.replace({"Gender":{'male':0,'female':1}},inplace=True)

In [ ]:
cal_data.head()

,User_ID,Gender,Age,Height,Weight,Duration,Heart_Rate,Body_Temp,Calories
0,14733363,0,68,190,94,29,105,40.8,231
1,14861698,1,20,166,60,14,94,40.3,66
2,11179863,0,69,179,79,5,88,38.7,26
3,16180408,1,34,179,71,13,100,40.5,71
4,17771927,1,27,154,58,10,81,39.8,35

In [ ]:
x=cal_data.drop(columns=['User_ID','Calories'],axis=1)
y=cal_data['Calories']

In [ ]:
print(x,y)

       Gender  Age  Height  Weight  Duration  Heart_Rate  Body_Temp
0           0   68     190      94        29         105       40.8
1           1   20     166      60        14          94       40.3
2           0   69     179      79         5          88       38.7
3           1   34     179      71        13         100       40.5
4           1   27     154      58        10          81       39.8
...       ...  ...     ...     ...       ...         ...        ...
14995       1   20     193      86        11          92       40.4
14996       1   27     165      65         6          85       39.2
14997       1   43     159      58        16          90       40.1
14998       0   78     193      97         2          84       38.3
14999       0   63     173      79        18          92       40.5

[15000 rows x 7 columns] 0        231
1         66
2         26
3         71
4         35
        ...
14995     45
14996     23
14997     75
14998     11
14999     98
Name: Calories, Length: 15000, dtype: int64

In [ ]:
x_train,x_test,y_train,y_test =train_test_split(x,y,test_size=0.2,random_state=2)

In [ ]:
print(x.shape,x_train.shape,x_test.shape)

(15000, 7) (12000, 7) (3000, 7)

In [ ]:
model=XGBRegressor()

In [ ]:
model.fit(x_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [ ]:
test_data_pred=model.predict(x_test)
print(test_data_pred)

[125.58828  222.11377   38.725952 ... 144.3179    23.425894  90.100494]

In [ ]:
mae=metrics.mean_absolute_error(y_test,test_data_pred)

In [ ]:
mae=metrics.mean_absolute_error(y_test,test_data_pred)

In [ ]:
input_data=[0 ,  69 ,  179.0   , 79.0  ,     5.0   ,     88.0,38.7]
print(input_data)

[0, 69, 179.0, 79.0, 5.0, 88.0, 38.7]

In [ ]:
input_data_np=np.asarray(input_data)
print(input_data_np)

input_reshape=input_data_np.reshape(1,-1)

[  0.   69.  179.   79.    5.   88.   38.7]

In [ ]:
pred=model.predict(input_reshape)
print(pred)

[24.628464]

In [ ]:
if pred[0] == 1:
  print("male")
else:
  print("female")

female

In [ ]:
import pickle

In [ ]:
filename='cal.sav'
pickle.dump(model,open(filename,'wb'))

In [ ]:
loaded_model=pickle.load(open('cal.sav','rb'))

In [ ]:
input_data=[0 ,  69 ,  179.0   , 79.0  ,     5.0   ,     88.0,38.7]
print(input_data)
input_data_np=np.asarray(input_data)
print(input_data_np)

input_reshape=input_data_np.reshape(1,-1)
pred=model.predict(input_reshape)
print(pred)
if pred[0] == 1:
  print("male")
else:
  print("female")

[0, 69, 179.0, 79.0, 5.0, 88.0, 38.7]
[  0.   69.  179.   79.    5.   88.   38.7]
[24.628464]
female

In [ ]:
for column in x.columns:
  print(column)

Gender
Age
Height
Weight
Duration
Heart_Rate
Body_Temp