In [ ]:
import pandas as pd
import numpy as np
import sklearn.datasets
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
game_df = pd.read_csv('/content/online_gaming_behavior_dataset - online_gaming_behavior_dataset.csv')

In [ ]:
game_df.head()

,PlayerID,Age,Gender,Location,GameGenre,PlayTimeHours,InGamePurchases,GameDifficulty,SessionsPerWeek,AvgSessionDurationMinutes,PlayerLevel,AchievementsUnlocked,EngagementLevel
0,9000,43,Male,Other,Strategy,16.271119,0,Medium,6,108,79,25,Medium
1,9001,29,Female,USA,Strategy,5.525961,0,Medium,5,144,11,10,Medium
2,9002,22,Female,USA,Sports,8.223755,0,Easy,16,142,35,41,High
3,9003,35,Male,USA,Action,5.265351,1,Easy,9,85,57,47,Medium
4,9004,33,Male,Europe,Action,15.531945,0,Medium,2,131,95,37,Medium

In [ ]:
game_df['EngagementLevel'].value_counts()

EngagementLevel
Medium    19374
High      10336
Low       10324
Name: count, dtype: int64

In [ ]:
game_x = game_df.drop(columns='EngagementLevel',axis=1)
game_y = game_df['EngagementLevel']

In [ ]:
game_model = LogisticRegression()

In [ ]:
game_encoder = LabelEncoder()

In [ ]:
game_df['Gender_Encoded'] = game_encoder.fit_transform(game_df['Gender'])
game_df['Location_Encoded'] = game_encoder.fit_transform(game_df['Location'])
game_df['GameGenre_Encoded'] = game_encoder.fit_transform(game_df['GameGenre'])
game_df['GameDifficulty_Encoded'] = game_encoder.fit_transform(game_df['GameDifficulty'])

In [ ]:
game_x_train, game_x_test, game_y_train, game_y_test = train_test_split(game_x.drop(['Gender','Location','GameGenre','GameDifficulty'], axis=1),game_y, test_size=0.1, random_state=2)

In [ ]:
game_model.fit(game_x_train, game_y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
game_x_pred = game_model.predict(game_x_train)
game_x_acc = accuracy_score(game_x_pred, game_y_train)

In [ ]:
print(game_x_acc)

0.5735498195947821

In [ ]:
game_test_pred = game_model.predict(game_x_test)
game_test_acc = accuracy_score(game_test_pred,game_y_test)

In [ ]:
print(game_test_acc)

0.5716783216783217

In [ ]:
game_df.head()

,PlayerID,Age,Gender,Location,GameGenre,PlayTimeHours,InGamePurchases,GameDifficulty,SessionsPerWeek,AvgSessionDurationMinutes,PlayerLevel,AchievementsUnlocked,EngagementLevel,Gender_Encoded,Location_Encoded,GameGenre_Encoded,GameDifficulty_Encoded
0,9000,43,Male,Other,Strategy,16.271119,0,Medium,6,108,79,25,Medium,1,2,4,2
1,9001,29,Female,USA,Strategy,5.525961,0,Medium,5,144,11,10,Medium,0,3,4,2
2,9002,22,Female,USA,Sports,8.223755,0,Easy,16,142,35,41,High,0,3,3,0
3,9003,35,Male,USA,Action,5.265351,1,Easy,9,85,57,47,Medium,1,3,0,0
4,9004,33,Male,Europe,Action,15.531945,0,Medium,2,131,95,37,Medium,1,1,0,2

In [ ]:
game_input_data = (9000,43,0,6,108,79,25,1)

game_input_data_np = np.asarray(game_input_data)
game_input_data_reshaped = game_input_data_np.reshape(1, -1)

game_pred = game_model.predict(game_input_data_reshaped)
print(game_pred)

['High']

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(