In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

In [ ]:
online=pd.read_csv('/content/online_course_engagement_data - online_course_engagement_data.csv')

In [ ]:
online.head()

,UserID,CourseCategory,TimeSpentOnCourse,NumberOfVideosWatched,NumberOfQuizzesTaken,QuizScores,CompletionRate,DeviceType,CourseCompletion
0,5618,Health,29.979719,17,3,50.365656,20.860773,1,0
1,4326,Arts,27.802640,1,5,62.615970,65.632415,1,0
2,5849,Arts,86.820485,14,2,78.458962,63.812007,1,1
3,4992,Science,35.038427,17,10,59.198853,95.433162,0,1
4,3866,Programming,92.490647,16,0,98.428285,18.102478,0,0

In [ ]:
online.shape

(9000, 9)

In [ ]:
online.isnull().sum()

UserID                   0
CourseCategory           0
TimeSpentOnCourse        0
NumberOfVideosWatched    0
NumberOfQuizzesTaken     0
QuizScores               0
CompletionRate           0
DeviceType               0
CourseCompletion         0
dtype: int64

In [ ]:
oc1=online.replace({'CourseCategory':{'Business':0,'Health':1,'Science':2,'Programming':3,'Arts':4}})

In [ ]:
print(oc1)

      UserID  CourseCategory  TimeSpentOnCourse  NumberOfVideosWatched  \
0       5618               1          29.979719                     17
1       4326               4          27.802640                      1
2       5849               4          86.820485                     14
3       4992               2          35.038427                     17
4       3866               3          92.490647                     16
...      ...             ...                ...                    ...
8995    8757               1          37.445225                     14
8996     894               2          48.631443                      7
8997    6323               1          38.212512                      3
8998    3652               1          70.048665                     13
8999    5595               1          93.589781                      7

      NumberOfQuizzesTaken  QuizScores  CompletionRate  DeviceType  \
0                        3   50.365656       20.860773           1
1                        5   62.615970       65.632415           1
2                        2   78.458962       63.812007           1
3                       10   59.198853       95.433162           0
4                        0   98.428285       18.102478           0
...                    ...         ...             ...         ...
8995                     4   54.469359       32.990704           1
8996                     7   59.413257        0.254625           0
8997                     3   69.508297       70.188159           1
8998                    10   79.655182       72.975225           1
8999                     5   56.274546       11.299071           0

      CourseCompletion
0                    0
1                    0
2                    1
3                    1
4                    0
...                ...
8995                 0
8996                 0
8997                 0
8998                 1
8999                 0

[9000 rows x 9 columns]

In [ ]:
x=oc1.drop(columns=['CourseCompletion'],axis=1)
y=oc1['CourseCompletion']

In [ ]:
print(x)

      UserID  CourseCategory  TimeSpentOnCourse  NumberOfVideosWatched  \
0       5618               1          29.979719                     17
1       4326               4          27.802640                      1
2       5849               4          86.820485                     14
3       4992               2          35.038427                     17
4       3866               3          92.490647                     16
...      ...             ...                ...                    ...
8995    8757               1          37.445225                     14
8996     894               2          48.631443                      7
8997    6323               1          38.212512                      3
8998    3652               1          70.048665                     13
8999    5595               1          93.589781                      7

      NumberOfQuizzesTaken  QuizScores  CompletionRate  DeviceType
0                        3   50.365656       20.860773           1
1                        5   62.615970       65.632415           1
2                        2   78.458962       63.812007           1
3                       10   59.198853       95.433162           0
4                        0   98.428285       18.102478           0
...                    ...         ...             ...         ...
8995                     4   54.469359       32.990704           1
8996                     7   59.413257        0.254625           0
8997                     3   69.508297       70.188159           1
8998                    10   79.655182       72.975225           1
8999                     5   56.274546       11.299071           0

[9000 rows x 8 columns]

In [ ]:
print(y)

0       0
1       0
2       1
3       1
4       0
       ..
8995    0
8996    0
8997    0
8998    1
8999    0
Name: CourseCompletion, Length: 9000, dtype: int64

In [ ]:
x_train,x_test,y_train,y_test =train_test_split(x,y,test_size=0.2,random_state=2)

In [ ]:
print(x_train.shape,x_test.shape,x.shape)

(7200, 8) (1800, 8) (9000, 8)

In [ ]:
model=LogisticRegression()

In [ ]:
model.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
pred_data=model.predict(x_train)

In [ ]:
acc_train=accuracy_score(y_train,pred_data)

In [ ]:
print(acc_train)

0.6515277777777778

In [ ]:
x_train_pred=model.predict(x_train)
x_train_acc=accuracy_score(x_train_pred,y_train)
print(x_train_acc)

0.6515277777777778

In [ ]:
x_test_pred=model.predict(x_test)
x_test_acc=accuracy_score(x_test_pred,y_test)
print(x_test_acc)

0.6177777777777778

In [ ]:
input_data=[4326,27.80263951,1,5,62.61596979,65.63241524,1,0]
input_data_np=np.asarray(input_data)
input_reshape=input_data_np.reshape(1,-1)
pred=model.predict(input_reshape)
print(pred)

[0]

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [ ]:
import pickle

In [ ]:
filename='online.sav'
pickle.dump(model,open(filename,'wb'))

In [ ]:
loaded_model=pickle.load(open('online.sav','rb'))

In [ ]:
input_data=[5618,1,29.979719346137415,17,3,50.365655948359226,20.860772712321186,1]
print(input_data)
input_data_np=np.asarray(input_data)
print(input_data_np)
input_data_re=input_data_np.reshape(1,-1)
pred=model.predict(input_data_re)
print(pred)
if pred[0] == 0:
  print("not CourseCompletion")
else:
  print("CourseCompletion")

[5618, 1, 29.979719346137415, 17, 3, 50.365655948359226, 20.860772712321186, 1]
[5.61800000e+03 1.00000000e+00 2.99797193e+01 1.70000000e+01
 3.00000000e+00 5.03656559e+01 2.08607727e+01 1.00000000e+00]
[0]
not CourseCompletion

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [ ]:
for column in x.columns:
  print(column)

UserID
CourseCategory
TimeSpentOnCourse
NumberOfVideosWatched
NumberOfQuizzesTaken
QuizScores
CompletionRate
DeviceType