In [ ]:
import pandas as pd
import numpy as np
import sklearn.datasets
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
weat_df = pd.read_csv('/content/weather_classification_data - weather_classification_data.csv')

In [ ]:
weat_df.head()

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility (km),Location,Weather Type
0,14,73,9.5,82,partly cloudy,1010.82,2,Winter,3.5,inland,Rainy
1,39,96,8.5,71,partly cloudy,1011.43,7,Spring,10.0,inland,Cloudy
2,30,64,7.0,16,clear,1018.72,5,Spring,5.5,mountain,Sunny
3,38,83,1.5,82,clear,1026.25,7,Spring,1.0,coastal,Sunny
4,27,74,17.0,66,overcast,990.67,1,Winter,2.5,mountain,Rainy

In [ ]:
weat_df.isnull().sum()

Temperature             0
Humidity                0
Wind Speed              0
Precipitation (%)       0
Cloud Cover             0
Atmospheric Pressure    0
UV Index                0
Season                  0
Visibility (km)         0
Location                0
Weather Type            0
dtype: int64

In [ ]:
weat_x = weat_df.drop(columns='Weather Type',axis=1)
weat_y = weat_df['Weather Type']

In [ ]:
print(weat_x)

       Temperature  Humidity  Wind Speed  Precipitation (%)    Cloud Cover  \
0               14        73         9.5                 82  partly cloudy
1               39        96         8.5                 71  partly cloudy
2               30        64         7.0                 16          clear
3               38        83         1.5                 82          clear
4               27        74        17.0                 66       overcast
...            ...       ...         ...                ...            ...
13195           10        74        14.5                 71       overcast
13196           -1        76         3.5                 23         cloudy
13197           30        77         5.5                 28       overcast
13198            3        76        10.0                 94       overcast
13199           -5        38         0.0                 92       overcast

       Atmospheric Pressure  UV Index  Season  Visibility (km)  Location
0                   1010.82         2  Winter              3.5    inland
1                   1011.43         7  Spring             10.0    inland
2                   1018.72         5  Spring              5.5  mountain
3                   1026.25         7  Spring              1.0   coastal
4                    990.67         1  Winter              2.5  mountain
...                     ...       ...     ...              ...       ...
13195               1003.15         1  Summer              1.0  mountain
13196               1067.23         1  Winter              6.0   coastal
13197               1012.69         3  Autumn              9.0   coastal
13198                984.27         0  Winter              2.0    inland
13199               1015.37         5  Autumn             10.0  mountain

[13200 rows x 10 columns]

In [ ]:
print(weat_y)

0         Rainy
1        Cloudy
2         Sunny
3         Sunny
4         Rainy
          ...
13195     Rainy
13196     Snowy
13197    Cloudy
13198     Snowy
13199     Rainy
Name: Weather Type, Length: 13200, dtype: object

In [ ]:
weat_scalar=StandardScaler()
weat_model= LogisticRegression()
label=LabelEncoder()
weat_df['Cloud_Cover_Encoded'] = label.fit_transform(weat_df['Cloud Cover'])
weat_df['Season_Encoded'] = label.fit_transform(weat_df['Season'])
weat_df['Location_Encoded'] = label.fit_transform(weat_df['Location'])

In [ ]:
weat_df['Cloud_Cover_Encoded'] = label.fit_transform(weat_df['Cloud Cover'])
weat_df['Season_Encoded'] = label.fit_transform(weat_df['Season'])
weat_df['Location_Encoded'] = label.fit_transform(weat_df['Location'])

In [ ]:
weat_model= LogisticRegression()

In [ ]:
label=LabelEncoder()

In [ ]:
weat_df.head()

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility (km),Location,Weather Type
0,14,73,9.5,82,partly cloudy,1010.82,2,Winter,3.5,inland,Rainy
1,39,96,8.5,71,partly cloudy,1011.43,7,Spring,10.0,inland,Cloudy
2,30,64,7.0,16,clear,1018.72,5,Spring,5.5,mountain,Sunny
3,38,83,1.5,82,clear,1026.25,7,Spring,1.0,coastal,Sunny
4,27,74,17.0,66,overcast,990.67,1,Winter,2.5,mountain,Rainy

In [ ]:
weat_df['Cloud_Cover_Encoded'] = label.fit_transform(weat_df['Cloud Cover'])
weat_df['Season_Encoded'] = label.fit_transform(weat_df['Season'])
weat_df['Location_Encoded'] = label.fit_transform(weat_df['Location'])

In [ ]:
weat_x_train,weat_x_test,weat_y_train,weat_y_test = train_test_split(weat_x.drop(['Cloud Cover','Season','Location'],axis=1),weat_y,test_size=0.2,random_state=2)
weat_model.fit(weat_x_train,weat_y_train)

In [ ]:
weat_train_pred = weat_model.predict(weat_x_train)
weat_train_acc = accuracy_score(weat_train_pred,weat_y_train)

In [ ]:
print(weat_train_acc)

0.8539772727272728

In [ ]:
weat_test_pred = weat_model.predict(weat_x_test)
weat_test_acc = accuracy_score(weat_test_pred,weat_y_test)

In [ ]:
print(weat_test_acc)

0.8492424242424242

In [ ]:
weat_df.head()

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility (km),Location,Weather Type,Cloud_Cover_Encoded,Season_Encoded,Location_Encoded
0,14,73,9.5,82,partly cloudy,1010.82,2,Winter,3.5,inland,Rainy,3,3,1
1,39,96,8.5,71,partly cloudy,1011.43,7,Spring,10.0,inland,Cloudy,3,1,1
2,30,64,7.0,16,clear,1018.72,5,Spring,5.5,mountain,Sunny,0,1,2
3,38,83,1.5,82,clear,1026.25,7,Spring,1.0,coastal,Sunny,0,1,0
4,27,74,17.0,66,overcast,990.67,1,Winter,2.5,mountain,Rainy,2,3,2

In [ ]:
weat_input_data = (14, 73, 9.5, 82, 1010.82, 2,3.5,)
weat_input_data_np = np.asarray(weat_input_data)
weat_input_data_reshaped = weat_input_data_np.reshape(1, -1)
weat_pred = weat_model.predict(weat_input_data_reshaped)
print(weat_pred)

['Rainy']

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(